<?php

/**
 * Debug Bar: panel "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;

?>
<style class="tracy-debug">

	#tracy-debug .tracy-SqlPanel h2 {
		font: 11pt/1.5 sans-serif;
		margin: 0;
		padding: 2px 8px;
		background: #3484d2;
		color: white;
	}

	#tracy-debug .tracy-SqlPanel table {
		width: 100%;
	}

	#tracy-debug #tracy-debug-panel-Tracy-Debugger-sql .tracy-SqlPanel table {
		background: #222;
		color:#fff;
	}

	#tracy-debug #tracy-debug-panel-Tracy-Debugger-sql .tracy-SqlPanel table:hover {
		background: #000;
	}

</style>


<h1>SQL</h1>

<div class="tracy-inner tracy-SqlPanel">
<?php foreach ($this->data as $item): ?>
	<?php if ($item['title']):?>
	<h2><?php echo htmlspecialchars($item['title']) ?></h2>
	<?php endif ?>

	<table>
	<?php $i = 0 ?>
	<tr class="<?php echo $i++ % 2 ? 'tracy-alt' : '' ?>">
		<td><?php echo $item['dump'] ?></td>
	</tr>
	</table>
<?php endforeach ?>
</div>
